### ISSUE TITLE
AssertionError: `output_dir` missing.

### ISSUE THREAD

**Issue by christophekey** [oandrienko/fast-semantic-segmentation#20]
```
` christophe@ubuntubox:~/Desktop/fast-semantic-segmentation$ python create_cityscapes_tfrecord.py -....

Traceback (most recent call last):
  File "create_cityscapes_tfrecord.py", line 140, in <module>
    tf.app.run()
  File "/home/christophe/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "create_cityscapes_tfrecord.py", line 108, in main
    assert FLAGS.output_dir, '`output_dir` missing.'
AssertionError: `output_dir` missing.`

Where am I going wrong with this? AssertionError: `output_dir` missing.
Many thanks.

**Comment by julienip** [comment]
Try : python create_cityscapes_tfrecord.py --output_dir="your_path"

**Comment by oandrienko** [comment]
Hey @christophekey, thanks for posting the issue. As @julienip points out, looks like you were just missing the output directory location for the TFRecord which is specified with the `output_dir` argument. If you have more trouble please feel free to reopen the issue.
