### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by IOEvan** [oandrienko/fast-semantic-segmentation#26]
Thanks for your sharing.

`ImportError: cannot import name hyperparams_pb2`

It couldn't find such file inside protos folder, so what should I do?

**Comment by IOEvan** [comment]
I have solved it!

**Comment by shakey-cuimiao** [comment]
@IOEvan 
When I finish compiling it appears to get protos，I get erros:
Traceback (most recent call last):
  File "train_mem_saving.py", line 39, in <module>
    from builders import model_builder
  File "/home/sherry/cuimiao/Fabric_defect_detection/fast-semantic-segmentation/builders/model_builder.py", line 8, in <module>
    from builders import hyperparams_builder
  File "/home/sherry/cuimiao/Fabric_defect_detection/fast-semantic-segmentation/builders/hyperparams_builder.py", line 9, in <module>
    from protos import hyperparams_pb2
ImportError: cannot import name 'hyperparams_pb2'
