### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by jinfagang** [oandrienko/fast-semantic-segmentation#7]
```
ImportError: cannot import name 'dilated_resnet_v1'
```

there were no such file inside third party folder

**Comment by jinfagang** [comment]
Dude.......... You should check that file before push to github............ that file no where to find and resnet_v1 were not used at all.............

**Comment by oandrienko** [comment]
@jinfagang Hey so sorry - totally my fault. I had accidentally added some changes a couple days ago that I didn't mean to push. Everything should work fine now.

**Comment by oandrienko** [comment]
For the latest commit, I've changed some of the protobuf files so you might need to run `protoc protos/*.proto --python_out=.` again. Thanks for your interest in the project!

**Comment by jinfagang** [comment]
@oandrienko That's a very quick response. I shall try it out.

**Comment by jinfagang** [comment]
@oandrienko There seems still got an error:

```
get all 628 images.
Traceback (most recent call last):
  File "inference.py", line 141, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "inference.py", line 138, in main
    label_map, output_directory)
  File "inference.py", line 82, in run_inference_graph
    label_color_map=label_color_map)
  File "/media/jintian/netac/ai/home/fast-semantic-segmentation/libs/exporter.py", line 64, in deploy_segmentation_inference_graph
    outputs = _get_outputs_from_inputs(model, input_tensor)
  File "/media/jintian/netac/ai/home/fast-semantic-segmentation/libs/exporter.py", line 38, in _get_outputs_from_inputs
    outputs_dict = model.predict(preprocessed_inputs)
  File "/media/jintian/netac/ai/home/fast-semantic-segmentation/architectures/icnet_architecture.py", line 111, in predict
    pooled_quarter_res = self._icnet_pspmodule(quarter_res)
  File "/media/jintian/netac/ai/home/fast-semantic-segmentation/architectures/icnet_architecture.py", line 172, in _icnet_pspmodule
    [input_h/2, input_w/2], stride=[input_h/2, input_w/2])
TypeError: unsupported operand type(s) for /: 'Dimension' and 'int'

```

I set image path to cityscapes video images. Is there any logical assertions or judgement?

**Comment by jinfagang** [comment]
OK, I got it

**Comment by oandrienko** [comment]
Okay great, I'm glad this works for you now! And thanks for posting that error above - I pushed a small fix that should prevent this in the future.
